### ISSUE TITLE
Not setting correct dbType

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_extend_settings#2]
I've moved the dbType setting from settings.json to credentials.json.  I set the dbType to mysql and set the dbSettings correctly.  When I run `./bin/run.sh` it's still using the dirty db settings, and I'm not sure why.

**Comment by cmbirk** [comment]
When I copy the mysql credentials back into `settings.json`, it runs correctly.

**Comment by JohnMcLear** [comment]
if you remove credentials.json do you get a warning on startup?

**Comment by JohnMcLear** [comment]
Also did you update etherpad to latest develop? :)

**Comment by JohnMcLear** [comment]
oh oh looks like I'm loading settings too late and database init is happening before..

**Comment by JohnMcLear** [comment]
leave this with me, will sort tomorrow.

**Comment by JohnMcLear** [comment]
I had to put this into core so please remove ep_extend_settings and update EP to latest develop

ta :)
